### ISSUE TITLE
NodeNotFoundError with CMS 3.1 and Django 1.8

### ISSUE THREAD

**Issue by mrsarm** [stefanfoulis/cmsplugin-filer#188]
I tried to create a new web site (not migrating from previous one). I installed a virtualenv with Python 3.4, Django 1.8 and CMS 3.1 and the latest version from repositories of this module and "django-filer" also.

When I run ``python manage.py migrate`` I get:

    Traceback (most recent call last):
      File "./manage.py", line 32, in <module>
        execute_from_command_line(sys.argv)
      File "/projects/mrsarm/py/mrdev/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
        utility.execute()
      File "/projects/mrsarm/py/mrdev/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/projects/mrsarm/py/mrdev/env/lib/python3.4/site-packages/django/core/management/base.py", line 393, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/projects/mrsarm/py/mrdev/env/lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
        output = self.handle(*args, **options)
      File "/projects/mrsarm/py/mrdev/env/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 93, in handle
        executor = MigrationExecutor(connection, self.migration_progress_callback)
      File "/projects/mrsarm/py/mrdev/env/lib/python3.4/site-packages/django/db/migrations/executor.py", line 19, in __init__
        self.loader = MigrationLoader(self.connection)
      File "/projects/mrsarm/py/mrdev/env/lib/python3.4/site-packages/django/db/migrations/loader.py", line 47, in __init__
        self.build_graph()
      File "/projects/mrsarm/py/mrdev/env/lib/python3.4/site-packages/django/db/migrations/loader.py", line 312, in build_graph
        _reraise_missing_dependency(migration, parent, e)
      File "/projects/mrsarm/py/mrdev/env/lib/python3.4/site-packages/django/db/migrations/loader.py", line 282, in _reraise_missing_dependency
        raise exc
      File "/projects/mrsarm/py/mrdev/env/lib/python3.4/site-packages/django/db/migrations/loader.py", line 308, in build_graph
        self.graph.add_dependency(migration, key, parent)
      File "/projects/mrsarm/py/mrdev/env/lib/python3.4/site-packages/django/db/migrations/graph.py", line 116, in add_dependency
        parent
    django.db.migrations.graph.NodeNotFoundError: Migration cmsplugin_filer_image.0001_initial dependencies reference nonexistent parent node ('filer', '0001_initial')

If I remove all cmsplugin-filer modules from the project (but without removing "django-filer") the migration runs ok.

This is my environment:

    Django==1.8.3
    Django-Select2==4.3.1
    Pillow==2.9.0
    South==1.0.2
    Unidecode==0.04.18
    argparse==1.3.0
    cmsplugin-filer==0.10.1
    cmsplugin-nivoslider==0.5.9
    dj-database-url==0.3.0
    django-admin-shortcuts==1.2.6
    django-appconf==1.0.1
    django-classy-tags==0.6.2
    django-cms==3.1.2
    django-filer==0.9.11
    django-mptt==0.7.4
    django-polymorphic==0.7.1
    django-reversion==1.8.5
    django-sekizai==0.8.2
    django-treebeard==3.0
    djangocms-admin-style==0.2.7
    djangocms-column==1.5
    djangocms-file==0.1
    djangocms-flash==0.2.0
    djangocms-googlemap==0.2
    djangocms-inherit==0.1
    djangocms-link==1.6.2
    djangocms-picture==0.1
    djangocms-snippet==1.5
    djangocms-style==1.5
    djangocms-teaser==0.1
    djangocms-text-ckeditor==2.5.2
    djangocms-video==0.1
    easy-thumbnails==2.2
    flake8==2.4.1
    html5lib==0.999
    linecache2==1.0.0
    mccabe==0.3.1
    mock==1.1.2
    pbr==1.3.0
    pep8==1.5.7
    pluggy==0.3.0
    py==1.4.30
    pyflakes==0.8.1
    pytz==2015.4
    six==1.9.0
    tox==2.1.1
    traceback2==1.4.0
    tzlocal==1.2
    unittest2==1.1.0
    virtualenv==13.1.0

**Comment by mrsarm** [comment]
This looks like an error in django-filer migration compatibility with Django 1.8.

I tried to install [cmsplugin-nivoslider](https://pypi.python.org/pypi/cmsplugin-nivoslider) module, and I had the same error.

I tested the same configuration before with Django CMS 3.0 and Django 1.6 and works.

**Comment by yakky** [comment]
@mrsarm which filer version are you using? Any configuration for ``MIGRATION_MODULES`` setting?

**Comment by mrsarm** [comment]
I tested first with version 0.9.11, and then with the latest "master" version from Github repository.

The ``settings.py``, ``requirements.txt`` and the full project is [here](https://github.com/mrsarm/django-mrdev-site), branch master.

If you see, there is a "cms-3.0" branch also, and has the same configuration (except minimal differences from CMS 3.0 to 3.1 configuration), and in that branch with these plugins works, so looks like an incompatibility issue from "filer" project, not the cmsplugin. Right?

**Comment by mrsarm** [comment]
The project has this commented in ``MIGRATION_MODULES`` just to work without *cmsplugin-filer*:

    #'cmsplugin_filer_file': 'cmsplugin_filer_file.migrations_django',
    #'cmsplugin_filer_folder': 'cmsplugin_filer_folder.migrations_django',
    #'cmsplugin_filer_link': 'cmsplugin_filer_link.migrations_django',
    #'cmsplugin_filer_image': 'cmsplugin_filer_image.migrations_django',
    #'cmsplugin_filer_teaser': 'cmsplugin_filer_teaser.migrations_django',
    #'cmsplugin_filer_video': 'cmsplugin_filer_video.migrations_django',

But of course, I tested all these with the code uncommented in my local environment.

**Comment by yakky** [comment]
filer 0.9.11 migrations are in usual ``filer.migrations`` module, so it must be removed from ``MIGRATION_MODULES``

**Comment by mrsarm** [comment]
Yes, that solves my problem, thanks. So, there is no bug :)
