### ISSUE TITLE
Fresh install of cmsplugin-filer gives migration error, nonexistent parent node (u'filer', u'0001_initial')

### ISSUE THREAD

**Issue by irslambouf** [stefanfoulis/cmsplugin-filer#189]
Hello,
did fresh install or cmsplugin-filer with pip install cmsplugin-filer added:
```
INSTALLED_APPS = (
    ....
    'filer',
    ...
    'cmsplugin_filer_file',
    'cmsplugin_filer_folder',
    'cmsplugin_filer_link',
    'cmsplugin_filer_image',
    'cmsplugin_filer_teaser',
    'cmsplugin_filer_video',
    ...
)
```
and
```
MIGRATION_MODULES = {
    'filer' : 'filer.migrations', 
     ...
    'cmsplugin_filer_file': 'cmsplugin_filer_file.migrations_django',
    'cmsplugin_filer_folder': 'cmsplugin_filer_folder.migrations_django',
    'cmsplugin_filer_link': 'cmsplugin_filer_link.migrations_django',
    'cmsplugin_filer_image': 'cmsplugin_filer_image.migrations_django',
    'cmsplugin_filer_teaser': 'cmsplugin_filer_teaser.migrations_django',
    'cmsplugin_filer_video': 'cmsplugin_filer_video.migrations_django',
}
```
try to run ./manage.py migrate, or makemigrations filer or runserver

and getting error:
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/bitnami/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/opt/bitnami/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/bitnami/python/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/opt/bitnami/python/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/opt/bitnami/python/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 63, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/opt/bitnami/python/lib/python2.7/site-packages/django/db/migrations/executor.py", line 17, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/opt/bitnami/python/lib/python2.7/site-packages/django/db/migrations/loader.py", line 48, in __init__
    self.build_graph()
  File "/opt/bitnami/python/lib/python2.7/site-packages/django/db/migrations/loader.py", line 245, in build_graph
    self.graph.add_dependency(migration, key, parent)
  File "/opt/bitnami/python/lib/python2.7/site-packages/django/db/migrations/graph.py", line 46, in add_dependency
    "Migration %s dependencies reference nonexistent parent node %r" % (migration, parent)
KeyError: u"Migration cmsplugin_filer_teaser.0001_initial dependencies reference nonexistent parent node (u'filer', u')
```

**Comment by jsma** [comment]
If you are installing the latest version of django-filer, you need to remove 'filer' from MIGRATION_MODULES. This is no longer necessary now that Django 1.7+ version of migrations are now in the standard location.

**Comment by irslambouf** [comment]
removed the filer migration module (was originally a suggestion to repair the problem from @ojii on #django-cms IRC). Still getting:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/bitnami/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/opt/bitnami/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/bitnami/python/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/opt/bitnami/python/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/opt/bitnami/python/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 57, in handle
    loader = MigrationLoader(None, ignore_no_migrations=True)
  File "/opt/bitnami/python/lib/python2.7/site-packages/django/db/migrations/loader.py", line 48, in __init__
    self.build_graph()
  File "/opt/bitnami/python/lib/python2.7/site-packages/django/db/migrations/loader.py", line 245, in build_graph
    self.graph.add_dependency(migration, key, parent)
  File "/opt/bitnami/python/lib/python2.7/site-packages/django/db/migrations/graph.py", line 46, in add_dependency
    "Migration %s dependencies reference nonexistent parent node %r" % (migration, parent)
KeyError: u"Migration cmsplugin_filer_teaser.0001_initial dependencies reference nonexistent parent node (u'filer', u'0001_initial')"
```

**Comment by martcot** [comment]
@irslambouf Did you find solution?

**Comment by losttrekker** [comment]
Yeah, I'm running into the exact same problem.  Was there a good solution?

**Comment by solitaireinfosys** [comment]
I am getting same error when run makemigration command
